### ISSUE TITLE
Webpack throws "Uncaught Error: define cannot be used indirect" after update from 5.3.2 to 5.4.0

### ISSUE THREAD

**Issue by barbalex** [pouchdb/pouchdb#5312]
### Environment (Node.js/browser/hybrid app/etc.)

browser

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

chrome, newest

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

not set

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

CouchDB

### Please describe your issue.

Using version 5.3.2 everything works.
When I update to version 5.4.0 (and change nothing else) I get the mentioned error in the console and the page does not render.
I believe this is thrown by webpack, see here: https://github.com/webpack/webpack/issues/138

I am using:

- Windows 10
- node 6.2.1
- webpack 1.13.1

**Comment by barbalex** [comment]
same happens in PouchDB v5.4.1

**Comment by nolanlawson** [comment]
Is this a command-line error or a runtime error? Do you have a script/project to reproduce?

**Comment by jl-** [comment]
Same here as a runtime error with
- pouchdb 5.4.2
- webpack 1.13.1
- electron 1.2.1(local database only)
- mac 10.11.5

The only code related to pouchdb in my case is
 ```javascript
import PouchDB from 'pouchdb'
```

**Comment by barbalex** [comment]
This was a runtime error.

The project I was having this on just underwent a major change (other database > refactored codebase, no more use of pouchdb), so I can't reproduce it any more (it would be time consuming to recreate the needed database).

Another project where I use pouchdb in the browser does not have this problem, at least not with version 5.4.2.
Yet another project where I use pouchdb in node does not have this problem either (with version 5.4.2).

Sorry to bug you without being able to follow up!

I am not closing as @jl- had this issue too.

**Comment by jl-** [comment]
> Another project where I use pouchdb in the browser does not have this problem, at least not with version 5.4.2.

Then I guess it most probably has something to do with my webpack config for the render process.
```javascript
{
  target: 'electron-renderer'
  output: {
    libraryTarget: 'umd'
    // ...
  }
  // ...
}
```

**Comment by jl-** [comment]
Maybe that's a compatibility issue of pouchdb and webpack? 
from  [webpack/webpack#138](https://github.com/webpack/webpack/issues/138)
```javascript
var b = define; // This results in 
         // "define cannot be used indirect", but it should be parsed as "renaming"
b(function() {});
```
Webpack seems to have fixed some cases for the `define` renaming according to webpack issue#138, Is it possible that  some pattern of `define` in pouchdb was not included?

**Comment by jl-** [comment]
fixed with noParse in webpack config, [ansman/validate.js#12](https://github.com/ansman/validate.js/issues/12)

```
{
  module: {
      noParse: /node_modules\/json-schema\/lib\/validate\.js/
  }
}
```

**Comment by nolanlawson** [comment]
`websql -> sqlite3 -> node-pre-gyp -> request -> json-schema` is where that comes from. So this is a bug in json-schema. In fact I found the exact issue: https://github.com/kriszyp/json-schema/issues/59

Looks like someone either needs to fix `json-schema` or we need to stop requiring it.

**Comment by nolanlawson** [comment]
Actually to be honest I cannot reproduce this issue @barbalex using the latest version of Webpack (1.13.1). And in fact we have tests in place to check that Webpack is working.

Here is a sample project; it works fine. Please modify this sample project until it fails; otherwise I don't know how to fix this: https://gist.github.com/nolanlawson/f198d8099a3452f9fad3168a5fda26f1

**Comment by barbalex** [comment]
as mentioned here: https://github.com/pouchdb/pouchdb/issues/5312#issuecomment-225507823 I am sorry for stirring this up as my project has radically changed and I can't reproduce this any more

feel free to close

thanks @nolanlawson for this great tool!

**Comment by nolanlawson** [comment]
Ah sorry @barbalex, missed that.

@jl- can you still reproduce? Did it turn out to be a PouchDB bug or something else?

**Comment by jl-** [comment]
I think that's not a bug of PouchDB but more like a `json-schema` one. After adding `noParse` for `json-schema`, it work, but without that, it still failed with the same error, and I also noticed `request -> json-schema` in the error trace stack.

**Comment by nolanlawson** [comment]
@jl- Thanks, but that's not quite my question... My question is whether it's PouchDB bringing in json-schema and causing the bug, or if some other dependency is bringing it in and causing the bug. Seems json-schema is used by a lot of libraries, but it's possible to include it in a harmless way (e.g. in PouchDB's case we don't export `request` or `websql` to the browser, so I believe we shouldn't affect your build).

You can test by removing `pouchdb` from your `dependencies` and see if you still get the bug.

**Comment by jl-** [comment]
@nolanlawson Sorry for the misunderstanding 😄 
If I comment out `import PouchDB from 'pouchdb'`, I won't get any error. For that, I think the error was raised by `json-schema` used by `pouchdb`.

**Comment by nolanlawson** [comment]
@jl- OK, that's helpful! In that case, could you please provide a small test case to reproduce? Note that I tried to reproduce above and failed; perhaps your project is using Webpack in some kind of special way, or you're using an older version of PouchDB, or...?

**Comment by jl-** [comment]
@nolanlawson Sure, [here](https://github.com/jl-/bronote/tree/pouchdb-issue-reproduce) is my repo for reproduce
- Everything works fine when pouchdb was loaded by using [\<script\>](https://github.com/jl-/bronote/blob/pouchdb-issue-reproduce/src/app/tpl.html#L19) , with or without `noParse` in [webpack config](https://github.com/jl-/bronote/blob/pouchdb-issue-reproduce/webpack.conf.js#L159)
- If you comment out the  [\<script\>](https://github.com/jl-/bronote/blob/pouchdb-issue-reproduce/src/app/tpl.html#L19) and `import PouchDB from 'pouchdb'` by activate [this](https://github.com/jl-/bronote/blob/pouchdb-issue-reproduce/src/modules/db.js#L1), error was raised
    - with `noParse`, the error was 
![qq20160616-2 2x](https://cloud.githubusercontent.com/assets/6291986/16106356/500e87f6-33c6-11e6-8db0-eee7f1629bed.png), which I think is another topic and my own responsibility.


    - without `noParse`, the error was
![qq20160616-4 2x](https://cloud.githubusercontent.com/assets/6291986/16106362/582bdde4-33c6-11e6-9099-d3cc094f85cb.png)

Hope this might help, thanks for your works indeed 👍.

**Comment by nolanlawson** [comment]
@jl- Hm, I ran `npm i && npm run dev` but I don't see the error anywhere. Instead I see:

![screenshot 2016-06-16 08 05 09](https://cloud.githubusercontent.com/assets/283842/16121696/18244236-3399-11e6-8430-67fe96d88095.png)

I'm on OS X Yosemite. Also one small thing: if you could trim down your example project so that it just reproduces the error, that would make it easier for us to understand what's going on.

**Comment by jl-** [comment]
@nolanlawson Ok, now only the root react component will be render, others are cut off.
And I remove all the imports of css/scss files, hopefully the errors above are gone. 
Please pull the `pouchdb-issue-reproduce` branch and see. It should be only the `define cannot be used indirect` error

**Comment by nolanlawson** [comment]
This seems to be a bug in Webpack's Hot Module loader, since it appears to only occur when Hot Module loading is activated. Also I notice that the bug is that it's using PouchDB's `lib/index.js` instead of `lib/index-browser.js` even though we have the correct `"browser"` switch inside of our `package.json` (see [these lines](https://github.com/pouchdb/pouchdb/blob/69996fcb5b64a967984eaca8b0de6a04dccd9d7b/packages/pouchdb/package.json#L55-L58)):

![screenshot 2016-06-16 18 11 55](https://cloud.githubusercontent.com/assets/283842/16138027/2b61d7aa-33ee-11e6-9077-746262756df2.png)

I'm not sure how to fix this, though, since I'm unfamiliar with Webpack's internals and the stacktrace is pretty cryptic.

**Comment by nolanlawson** [comment]
BTW as a workaround you can use `pouchdb-browser` instead of `pouchdb`.

**Comment by nolanlawson** [comment]
I'm sorry to keep asking favors of you @jl-, but if we're going to get to the bottom of this issue, we'll really need to have a minimal example to reproduce. I can open an issue on the Webpack devs about this, but undoubtedly their first complaint will be that it's hard to tease out exactly what the cause is here, because there's just so much code.

I don't have any more time to look at this today, but if you could remove code until the issue no longer persists, and then add the code that causes it to reproduce, that would be very helpful.

I tried to tweak the config to change the result, but honestly I can't tell what's going on between `webpack-dev-server.js` and `webpack.conf.js` (I've never used Webpack).

**Comment by jl-** [comment]
No problem, I will try to make a minimal example from the current branch ASAP.

**Comment by jl-** [comment]
@nolanlawson  Ok, take a look [this](https://github.com/jl-/bronote/tree/pouchdb-issue-reproduce), I've removed almost all irrelevant code and simplify project structure.
Relevant lines are [noParse](https://github.com/jl-/bronote/blob/pouchdb-issue-reproduce/webpack.conf.js#L72) and [import Pouchdb](https://github.com/jl-/bronote/blob/pouchdb-issue-reproduce/src/modules/db.js#L1). make a `git pull`, `npm dev` to see if it works for you

**Comment by nolanlawson** [comment]
I took a second look, but I'm sorry to say I just can't figure out what's going on here. The bug is that Webpack (or some third-party library) is using `pouchdb/lib/index.js` instead of `pouchdb/lib/index-browser.js`, i.e. it's using the Node version of PouchDB rather than the browser version (as specified by the `"browser"` field in `package.json`). Luckily there is a workaround, which is to just use the `pouchdb-browser` package instead of `pouchdb`.

The bug, as far as I can tell, could exist anywhere in `webpack`, `webpack-dev-middleware`, `webpack-dev-server`, `webpack-hot-middleware`, `react-hot-loader`, one of the various Babel plugins, one of the various Webpack loaders, etc. etc. I appreciate your efforts to trim it down, but this is still a huge project with tons of dependencies, and I think it would be a large amount of effort on my part just to figure out what's calling what where.

If you would like more movement on this, I suggest filing your issue on Webpack and hoping that they can triage it appropriately. On the PouchDB side, I think we can confidently say that it's not our bug, and there are workarounds, so I'm going to go ahead and close this issue. Sorry I couldn't be more help. :(

**Comment by jl-** [comment]
Using `pouchdb-browser` is ok, thanks :)

**Comment by barbalex** [comment]
Thoroughly appreciate you effort!

**Comment by Nishanth2** [comment]
Using Pouchdb-browser or Pouchdb-node or Pouchdb ,,

Getting The same Error 
**Uncaught Error: define cannot be used indirect  amd-define.js:1**

Is there Any solution for it ?
 I am using Electron + Anuglar 2+ webpack 1.13.2

**Comment by barbalex** [comment]
@Nishanth2 did you try pouchdb-browser?

**Comment by nolanlawson** [comment]
We have tests in place to ensure that Webpack is working. We also have a sample app for Electron: https://github.com/nolanlawson/hello-electron-with-pouchdb. If that's not the case, please create a reproducible test case and file it on the repo. :)

**Comment by Nishanth2** [comment]
@barbalex  Yes I tried Pouchdb-browser .. Still got The same error only
