### ISSUE TITLE
Leveldown as optionalDependencies in 5.4.0

### ISSUE THREAD

**Issue by KRuelY** [pouchdb/pouchdb#5315]
### Environment (Node.js/browser/hybrid app/etc.)

(Node.js.)

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

(PouchDB.)

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

Hi, I've been using pouchdb 5.3.2 for my development. I am using it for starting up local server and testing. Currently I have a .npmrc that set optional=false, which will ignore all of the optionalDependencies(including pouchdb's optionalDependencies leveldown). I do not have leveldown as dependencies in my project.

After the 5.4.0 update, all of my tests are failing due to 
```
Error: the 'leveldown' package is not available. install it, or, specify another storage backend using the 'db' option
```
My thought is either leveldown should now be a dependency(?) for pouchdb(or pouchdb's dependencies?) instead of optionalDependency, or there is a specific new feature that I am using in pouchdb that require leveldown(but I don't have any code changes on my side). I'm having a hard time finding what changes from 5.3.2 to 5.4.0 that causes this issue. Do you guys have some hints that can help me find out what my problem is?

Thank you, and please correct me if I'm wrong because I'm still not familiar.

**Comment by daleharvey** [comment]
If you are running the nodejs test suite without giving it an alternative level adapter, you need leveldown installed (ie to not ignore it as an optional dependency), it is there as an optional dependency because other people do not have to (or cannot) install leveldown and arent testing against it

**Comment by daleharvey** [comment]
We also have an issue with optional dependencies not always installing correctly, you may need to manually `npm install leveldown`, that work is being tracked in https://github.com/pouchdb/pouchdb/issues/5257

Feel free to ask follow on questions, but closing as not a bug

**Comment by KRuelY** [comment]
Hi,

I know the changes that break my components. It is this line

https://github.com/pouchdb/pouchdb/blob/5.4.1/lib/index.js#L5064

In the 5.3.2 version, the requireLevelDown function is optional:

https://github.com/pouchdb/pouchdb/blob/5.3.2/src/adapters/leveldb/index.js#L175

**Comment by nolanlawson** [comment]
Whoops, looks like an error that accidentally snuck in during the monorepo changes.

**Comment by nolanlawson** [comment]
As a workaround, you can use a custom build that uses `node-websql` or `memory` or something along those lines. Check out the `pouchdb-memory` project for an example of this, or https://pouchdb.com/custom.html for details.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/6beb9aed0c6d0342a2b557c38c01d23c5de45592

**Comment by KRuelY** [comment]
Hi,

As I mentioned in the previous comments:

The levelDownPouch function always set .migrate to true:
https://github.com/pouchdb/pouchdb/blob/5.4.2/lib/index.js#L5083

In the LevelPouch$1 function, the condition:
https://github.com/pouchdb/pouchdb/blob/5.4.2/lib/index.js#L3748
will always go to the else block(which requires leveldown) unless we have the noMigrate sets to true.

What do the migrate and noMigrate mean in this context? 

Thanks and sorry for not being clear.

**Comment by nolanlawson** [comment]
Crap yeah, there is still a bug in here.

`opts.migrate` and `opts.noMigrate` are dumb internal options that we created and did not document in order to work around disabling migrations for non-`leveldown` DBs. Unfortunately it looks like we did not solve this because we always set `migrate` to true.

We should remove `noMigrate` since it's not necessary if we already have `migrate`.

**Comment by nolanlawson** [comment]
Fixed. BTW @KRuelY you can still work around this problem by using the custom builds.

**Comment by KRuelY** [comment]
@nolanlawson Hi, thanks for explaining it to me and the custom builds. I'll take a look at the custom build but I just thought that it would be great to submit the issue because I'm not in a hurry. Thanks guys for being helpful!

One more question: are you guys still supporting the pouchdb express? It is currently giving deprecated warnings due to the callback such as

https://github.com/pouchdb/express-pouchdb/blob/master/lib/utils.js#L74

It's just a minor thing though. Once again, thanks!

**Comment by nolanlawson** [comment]
It's still supported; it just needs an update.

**Comment by daleharvey** [comment]
fixed again in https://github.com/pouchdb/pouchdb/commit/584d5a4f4884b9e178fa8f045f9be137378de203
