### ISSUE TITLE
RFC: PouchDB lite

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5804]
### The problem

PouchDB is still pretty large, even with the new multi-package build. Just `pouchdb-core`, `pouchdb-adapter-http`, `pouchdb-adapter-idb`, and `pouchdb-replication` (i.e. the minimum for a replicating IndexedDB) comes out to about 37kB. By comparison, jQuery is ~30kB and many modern frameworks like Vue.js are ~29kB even with extra features (such as the router and vuex).
### Proposed solution

I'd like to make a "lite" version of PouchDB with the following changes:
- no `debug`
- no `lie` (just use Promise)
- Promise API only, no callback API
- no migrations
- no attachment support
- no mapreduce
- no websql
- idb just runs everywhere instead of checking for Safari

With these changes, I believe we can create a build that's around ~15kB (that's my goal anyway). Then we can just include it as `lib/pouchdb-lite.js` (browserify/webpack) and/or `dist/pouchdb-lite.js`.
### How?

I don't believe we can get many more gains from modularity. Unfortunately it's just hard to split off unnecessary stuff while still making it composable.

However, we can just add switches like this to our codebase:

``` js
if (!process.env.POUCHDB_LITE) {
  // bunch of code here
}
```

And then using `rollup-plugin-replace` we can turn `process.env.POUCHDB_LITE` into a `true` or a `false` as necessary, and Rollup's dead code elimination takes care of the rest.

What do y'all think of this? Is this a bonkers idea? Should we just wait for idb-next? (Personally I don't think so, and I think an extra "lite" build has value, but it's up for debate! :smiely:)

**Comment by daleharvey** [comment]
I am definitely +1 on reducing the build size. Similiarly with `idb-next` although I am worried about spreading dev effort to thin and giving users confusing choices to make. I think where we can make improvements in the current build we do, and if we were to produce an alternative build I think we should coordinate on doing it once.

So first to address issues which I think can be reasonably easily addressed in the current build:

 * `debug` - We have always talked about having builds without debug, I think ideally our `min.js` is considered a 'production' build that does not include debug
 * `lie` - I think we should remove this, users doing modern web dev in ie know that a promise polyfill is required and its considered best practice for libraries to not include their own versions of these polyfills

**Comment by daleharvey** [comment]
As for the rest, I would love to see if would could set a plan based on `idb-next` for this, I also want this to be vastly reduced size build, supporting idb only, moving migrations into a seperate package, dropping mapreduce (but supporting .find). However even if you find it easier to do this from scratch then at some point in the future we can hopefully look at converging them (I would very much like to see the pouchdb release focus around a single `pouchdb` and until lite/next is ready to replace that then they stay as "extras")

I havent had a lot of time to work on `next` for a while, but November I am going to have a large amount of time to dedicate to getting secondary indexes working and general pouch work

**Comment by nickcolley** [comment]
👍  Also agree that things like debug could be only stripped from the production build similar to how the React time strips variant debug messages from production builds..

**Comment by nolanlawson** [comment]
I agree with you on both `debug` and `lie`, but unfortunately those two alone will only remove about 3kB min+gz total. Hence my desire to be even more aggressive. :) In any case, we can certainly remove them for v7; I think the ecosystem is ready for a library that requires `Promise` and I think only including `debug` in the minified prod version makes sense. Note though that it doesn't solve the problem for browserify/webpack users, whereas my suggestion here would.

`idb-next` is a separate discussion in my mind. TBH I'm still unsure about how to proceed with it, because we have to be very clear about the messaging since it's a breaking change with the previous version of Pouch. People need to understand that it's not just a breaking change; it's a change where they'll have to migrate existing user data.

BTW I think we should also consider unblocking Safari 10 from IDB, but sadly there hasn't been much movement in #5572 . I'll try to look into that when I have a moment, but I admit I am stretched extremely thin these days.

**Comment by paulocoghi** [comment]
> I think the ecosystem is ready for a library that requires `Promise` and I think only including debug in the minified prod version makes sense.

Totally agree. :thumbsup:

**Comment by nolanlawson** [comment]
Made some progress on this. Using [this branch](https://github.com/pouchdb/pouchdb/tree/pouchdb-lite), adding `if (process.env.POUCHDB_LITE) {}` annotations, removing debug, lie, pouchdb-mapreduce, pouchdb-adapter-websql, and any migrations for idb, we're already down to 100K from 140K (for pouchdb.min.js, not counting gzip). I think I can get it even lower if I remove attachment support, since that will drop spark-md5 and a bunch of attachment-specific code for dealing with Blobs.

**Comment by nolanlawson** [comment]
Current discify view for the "lite" build (spark-md5 can potentially be removed, so can vuvuzela but it's barely worth it):

![screenshot 2016-11-19 18 32 50](https://cloud.githubusercontent.com/assets/283842/20459889/f21a88f2-ae86-11e6-95e2-a6bf6951f053.png)

**Comment by nolanlawson** [comment]
Removing Map, Set, XMLHttpRequest (use fetch instead), all Blob stuff, all attachment stuff, Chrome app support, it's down to 25460 bytes min+gz and 77761 bytes without gzip.

**Comment by nolanlawson** [comment]
Combined with other recent PRs (on fetch, process.nextTick, and simpler PouchErrors), it's down to 24361 bytes min+gz, 74008 without gzip. I was hoping to get it to sub-20KB. :confused: Might need more work even outside of `if (process.env.POUCHDB_LITE) {}` annotations.

**Comment by nolanlawson** [comment]
Not so sure this is a good idea anymore. I think we can improve the size of core PouchDB without having an entirely separate build process.

E.g. we could fork spark-md5 to use Rollup/modules, we could clean up our repetitive codebase, and we could create a no-polyfill build without lie, Map, Set, fetch polyfill, etc.
