### ISSUE TITLE
Dependency leveldown@3.0.0 can't be installed on newest nodejs (12.0.x) as node-gyp has a problem

### ISSUE THREAD

**Issue by taschana** [pouchdb/pouchdb#7754]
### Issue
PouchDB cannot be installed with current NodeJS version.

### Info
- Environment: **Node.js 12.1.0** (installed the .msi with the checkbox "install all necessary things" checked
- Environment in which it is working: Node.js 8.9.4 (I've not checked all versions inbetween those two, but know that this one here is working on 2 different machines)
- Platform: Windows 10 (64bit) as well as Ubuntu 18.04.2 (64bit)
- Adapter: 
- package: PouchDB

### Reproduce
trying to install pouchdb on EMPTY project (as well as bigger project, same outcome!) 
`npm install pouchdb --save`
Getting the error that building leveldown@3.0.0 isn't working (some node-gyp problem).
Installing the newest version of leveldown (5.0.3) works, but doesn't prevent pouchdb from installing leveldown@3.0.0, thus it isn't a workaround.

last bit of the error message, after tons of building-error-messages (see attached log).
```
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\projects\electron-pouchdb\node_modules\pouchdb\node_modules\leveldown
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN cms@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
```

I've attached a log file and the package.json

[2019-05-05T14_27_21_342Z-debug.log](https://github.com/pouchdb/pouchdb/files/3145636/2019-05-05T14_27_21_342Z-debug.log)
[package.json.zip](https://github.com/pouchdb/pouchdb/files/3145637/package.json.zip)

Please update the package to some leveldown dependency where leveldown can be installed. Thank you!

**Comment by AJHenry** [comment]
I was able to fix this with `npm install -g windows-build-tools`

**Comment by taschana** [comment]
Tried on another machine with Node 10.13.0 -- also failing on leveldown@3.0.0

[2019-05-07T10_14_48_929Z-debug.log](https://github.com/pouchdb/pouchdb/files/3152053/2019-05-07T10_14_48_929Z-debug.log)

**Comment by taschana** [comment]
#7747

**Comment by taschana** [comment]
#7748

**Comment by taschana** [comment]
Not sure why it doesn't show here, but I got an email saying someone fixed it with
`I was able to fix this with npm install -g windows-build-tools`

I haven't tried that, as I fixed it using the github-install-method, but in case someone else has the problem and wants to give it a try, I mentioned it here. Thanks to the sender of the email, and sorry if I just didn't find your comment.

**Comment by taschana** [comment]
Okay guys,
I'm not super experienced with this, nor am I sure if I'm asking the wrong people, but if anyone could tell me why the f*** electron constantly tells me it doesn't find pouchdb, I'd be delighted.

[electron-pouch.zip](https://github.com/pouchdb/pouchdb/files/3161936/electron-pouch.zip)

**Comment by chisNaN** [comment]
Hello @taschana 
i have tried to import with an absolute path which seems to find the module
but after i have another fatal syntax error
```sh
import PouchDB from 'pouchdb-core';
       ^^^^^^^

SyntaxError: Unexpected identifier
```

i am not familiar with electron.

For the moment you can try my "solution" above to install pouch7 normally but adding a RESOLUTION section in the package.json if leveldown still not deployed to npm registry

**Comment by taschana** [comment]
Node v.11 (latest) plus resolution part mentioned by you gets this error:
```
App threw an error during load
Error: The module '\\?\D:\projects\electron-pouch\node_modules\level\node_modules\leveldown\build\Release\leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 67. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:155:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:850:18)
    at Object.func [as .node] (electron/js2c/asar.js:155:31)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at bindings (D:\projects\electron-pouch\node_modules\bindings\bindings.js:84:48)
    at Object.<anonymous> (D:\projects\electron-pouch\node_modules\level\node_modules\leveldown\leveldown.js:4:46)
```

node v.12 with resolution part in package.json still tries to install leveldown@3.0.0
```
> leveldown@3.0.0 install D:\projects\electron-pouch\node_modules\pouchdb\node_modules\leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.1.0 runtime=node arch=x64 platform=win32)
```

This thing doesn't run in any configuration.
The syntax error should only be because I am babel-ing this from es6 to es5 for Electron. It is later 
```
var _electron = require("electron");
var _path = require("path");
var _path2 = _interopRequireDefault(_path);
var _pouchdb = require("pouchdb");
```

**Comment by taschana** [comment]
Okay. Reason enough to simply wait for the next release. It is broken at the moment.

**Comment by chisNaN** [comment]
Yes better wait for the release than waste too much of your time for this
