### ISSUE TITLE
Packages incompatible with NodeJS 12

### ISSUE THREAD

**Issue by wolfy1339** [pouchdb/pouchdb#7778]
### Issue
The Packages are incompatible with NodeJS 12

### Info
- Environment: Node.JS
- Platform: N/A
- Adapter: n/a
- Server: n/a

### Reproduce
Just install nodejs 12 and install pouchdb, and it will fail because the dependency on leveldown is out of date in the published version, but this issue is fixed in the master branch.

So can you please make a new patch release from master to mitigate these problems?

**Comment by ghaschel** [comment]
It happened to me on Mac OS Mojave in nodejs 12.
Had to downgrade to 10.15.0 and install xcode in order to compile the binaries

**Comment by wolfy1339** [comment]
I've searched previous issues and apparently this is known to them, and the only workaround is to install from the git repo.

They should really just make a new release to fix that problem

**Comment by pburgmer** [comment]
Doesn't work on me either. It would be great if this could be fixed.

**Comment by wookoouk** [comment]
Can confirm, `npm install pouchdb/pouchdb#master` works on nodejs 12

**Comment by jeremad** [comment]
This is is fixed on master, I don't know why it is not released yet...

**Comment by garrensmith** [comment]
Hopefully I will get a release out soon

**Comment by wookoouk** [comment]
Is this issue resolved?

**Comment by garrensmith** [comment]
It will be in the next release


________________________________

**Comment by wolfy1339** [comment]
And the next release isn't cut yet. And this is still a problem for people currently

**Comment by daleharvey** [comment]
And @garrensmith is working on the new release, including closing issues that have been fixed in master so we can keep track of what are fixed issues and what remains.

That is our current workflow, please avoid commenting unless you have something useful to add as anything else just distracts from doing the actual release
